services:
  node-prod:
    build:
      context: .
      target: build-prod
    container_name: standards-node-prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3052:3052"

  redis:
    container_name: standards-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
