apiVersion: v1
kind: Secret
metadata:
  name: applying-service-standards-dev-secrets
type: Opaque
stringData:
  GOV_NOTIFY_API_KEY: "${GOV_NOTIFY_API_KEY}"
  BASIC_AUTH_USER: "${BASIC_AUTH_USER}"
  BASIC_AUTH_PASS: "${BASIC_AUTH_PASS}"
  CONTENTFUL_SPACE_ID: "${CONTENTFUL_SPACE_ID}"
  CONTENTFUL_DELIVERY_API_TOKEN: "${CONTENTFUL_DELIVERY_API_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: Opaque
data:
  auth: "${BASIC_AUTH_BASE64}"
