apiVersion: v1
kind: Secret
metadata:
  name: applying-service-standards-dev-secrets
type: Opaque
stringData:
  GOV_NOTIFY_API_KEY: "${GOV_NOTIFY_API_KEY}"
  CONTENTFUL_SPACE_ID: "${CONTENTFUL_SPACE_ID}"
  CONTENTFUL_DELIVERY_API_TOKEN: "${CONTENTFUL_DELIVERY_API_TOKEN}"
  EXPRESS_SESSION_SECRET: "${EXPRESS_SESSION_SECRET}"
  OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
